# Generated by Django 6.1.1 on 2026-10-07 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('venue', 'Venue'), ('catering', 'Catering'), ('photography', 'Photography'), ('videography', 'Videography'), ('decoration', 'Decoration'), ('music', 'Music'), ('dj', 'DJ'), ('transport', 'Transport'), ('accommodation', 'Accommodation'), ('beauty', 'Beauty'), ('clothing', 'Clothing'), ('cake', 'Cake'), ('other', 'Other')], default='other', max_length=30)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('contacted', 'Contacted'), ('negotiating', 'Negotiating'), ('booked', 'Booked'), ('rejected', 'Rejected')], default='prospect', max_length=20)),
                ('quoted_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='events.event')),
            ],
        ),
    ]
