# Generated by Django 6.1.1 on 2026-10-05 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('group', models.CharField(choices=[('family', 'Family'), ('friends', 'Friends'), ('work', 'Work'), ('vip', 'VIP'), ('other', 'Other')], default='other', max_length=20)),
                ('side', models.CharField(choices=[('partner_one', 'Partner one'), ('partner_two', 'Partner two'), ('both', 'Both'), ('none', 'None')], default='none', max_length=20)),
                ('plus_one_allowed', models.BooleanField(default=False)),
                ('plus_one_name', models.CharField(blank=True, max_length=200)),
                ('rsvp_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('meal_preference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('table', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event')),
            ],
        ),
    ]
