# Generated by Django 6.1.1 on 2026-10-05 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('venue', 'Venue'), ('catering', 'Catering'), ('photography', 'Photography'), ('decoration', 'Decoration'), ('music', 'Music'), ('clothing', 'Clothing'), ('transport', 'Transport'), ('accommodation', 'Accommodation'), ('other', 'Other')], default='other', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='events.event')),
            ],
        ),
    ]
